# Generated by Django 3.2.5 on 2021-07-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210727_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_headline',
            new_name='sub_heading',
        ),
    ]
